### PR TITLE
Quick and dirty null-safety

### PR DESCRIPTION
**Pull request by DanMossa**
This is strictly using the null-safety migration tool and then manually fixing any errors that occur.

This is better than not being allowed to use this package due to it not supporting null-safety

### CODE REVIEW

**Comment by InvenceSaltillo** [comment]
I had this error when i tried to add git repository on my pubspec.yaml
Git error. Command: `git clone --mirror git@github.com:DanMossa/PersistentBottomNavBar.git /Users/riojas/development/flutter/.pub-cache/git/cache/PersistentBottomNavBar-2ac678e5e622d06347c44c624f23c34e8cf88975`

stdout: 

stderr: Cloning into bare repository '/Users/riojas/development/flutter/.pub-cache/git/cache/PersistentBottomNavBar-2ac678e5e622d06347c44c624f23c34e8cf88975'...

Host key verification failed.

fatal: Could not read from remote repository.



Please make sure you have the correct access rights

and the repository exists.

exit code: 128

pub get failed (server unavailable) -- attempting retry 1 in 1 second...

**Comment by DanMossa** [comment]
@InvenceSaltillo  I'm unsure if that's an issue from my end or yours.
What happens when you try to clone via http?

**Comment by DanMossa** [comment]
> This happens when iI try to clone from terminal...
> 
> `git clone [git@github.com](mailto:git@github.com):DanMossa/PersistentBottomNavBar.git
> Clonando en 'PersistentBottomNavBar'...
> The authenticity of host 'github.com (140.82.112.3)' can't be established.
> RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
> Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
> Warning: Permanently added 'github.com,140.82.112.3' (RSA) to the list of known hosts.
> [git@github.com](mailto:git@github.com): Permission denied (publickey).
> fatal: No se pudo leer del repositorio remoto.
> 
> Por favor asegúrate que tienes los permisos de acceso correctos
> y que el repositorio existe.`

Right. What happens when you clone via http?

**Comment by InvenceSaltillo** [comment]
Ready! I had problems with my ssh keys

**Comment by DanMossa** [comment]
No longer necessary !

**Comment by BilalShahid13** [comment]
Thank you for your effort!

**Pull request closed without merging**
